const Menu = [
  {
    id: "1",
    image: "image/noodle.jpg",
    name: "Maggie",
    price: "$ 12",
    category: "Breakfast",
    image: "image/noodle.jpeg",

    description: "I love maggie.Its very delicious.You must try.",
  },
  {
    id: "2",
    image: "image/chola-bhatura.jpg",
    name: "Chola-bhatura",
    price: "$ 18",
    category: "Breakfast",
    image: "image/chola-bhatura.jpg",
    description: "I love maggie.Its very delicious.You must try.",
  },
  {
    id: "3",
    image: "image/pasta.webp",
    name: "Pasta",
    price: "$ 19",
    category: "Breakfast",
    image: "image/pasta.webp",

    description: "I love maggie.Its very delicious.You must try.",
  },
  {
    id: "4",
    image: "image/pav-bhaji.jpg",
    name: "Pav-bhaji",
    price: "$ 12",
    category: "Lunch",
    image: "image/pav-bhaji.jpeg",
    description: "I love maggie.Its very delicious.You must try.",
  },
  {
    id: "5",
    image: "image/pizza.jpeg",
    name: "Pizza",
    price: "$ 12",
    category: "Lunch",
    image: "image/pizza.jpeg",
    description: "I love maggie.Its very delicious.You must try.",
  },
  {
    id: "6",
    image: "image/sandwiches.jpg",
    name: "Sandwiches",
    price: "$ 12",
    category: "Breakfast",
    image: "image/sandwiches.jpg",
    description: "I love maggie.Its very delicious.You must try.",
  },
  {
    id: "7",
    image: "image/shahi-paner.jpg",
    name: "Shahi-paneer",
    price: "$ 12",
    category: "Lunch",
    image: "image/shahi-paner.jpg",
    description: "I love maggie.Its very delicious.You must try.",
  },
  {
    id: "8",
    image: "image/soup.jpeg",
    name: "Soup",
    price: "$ 21",
    category: "Dinner",
    image: "image/soup.jpeg",
    description: "I love Soup.Its very delicious.You must try.",
  },
  {
    id: "9",
    image: "image/sweet.jpeg",
    name: "Sweet",
    price: "$ 21",
    category: "Dinner",
    image: "image/sweet.jpeg",
    description: "I love Sweet.Its very delicious.You must try.",
  },
];
export default Menu;
